name: Lint Python issues

on:
  push:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  python-lint-job:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # required to upload the SARIF to code-scanning
      security-events: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: VCS Diff Lint
        uses: fedora-copr/vcs-diff-lint-action@3fe529c95a55cf7d25d1ef73d53f790710c9a352 # v1.10.0
        id: VCS_Diff_Lint
        with:
          install_rpm_packages: |
            python3-dnf python3-httpx python3-packaging

      - name: Upload artifact with detected defects in SARIF format
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: VCS Diff Lint SARIF
          path: ${{ steps.VCS_Diff_Lint.outputs.sarif }}
        if: ${{ always() }}

      - name: Upload SARIF to GitHub using github/codeql-action/upload-sarif
        uses: github/codeql-action/upload-sarif@ae9ef3a1d2e3413523c3741725c30064970cc0d4 # v3.32.5
        with:
          sarif_file: ${{ steps.VCS_Diff_Lint.outputs.sarif }}
        if: ${{ always() }}

  ruff-format-job:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Ruff format check
        run: pipx run ruff format --check --diff .
