name: Lint Python issues

on:
  push:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  python-lint-job:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # required to upload the SARIF to code-scanning
      security-events: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: VCS Diff Lint
        uses: fedora-copr/vcs-diff-lint-action@58d42564182d60919f728e8428d5858ca7ffcc05 # v1.19.0
        id: VCS_Diff_Lint
        with:
          install_rpm_packages: |
            python3-dnf python3-httpx python3-packaging python3-pytest

      - name: Upload artifact with detected defects in SARIF format
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: VCS Diff Lint SARIF
          path: ${{ steps.VCS_Diff_Lint.outputs.sarif }}
        if: ${{ always() }}

      - name: Upload SARIF to GitHub using github/codeql-action/upload-sarif
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          sarif_file: ${{ steps.VCS_Diff_Lint.outputs.sarif }}
        if: ${{ always() }}

  ruff-format-job:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Ruff format check
        run: pipx run ruff format --check --diff .
